### ISSUE TITLE
IOError: [Errno Input overflowed] -9981

### ISSUE THREAD

**Issue by chaoming** [Uberi/speech_recognition#51] opened 2015-07-29 09:46 UTC
I got this error after the recognition worked OK once.

Source code:

```
import speech_recognition as sr

r = sr.Recognizer()
m = sr.Microphone()
m.RATE = 44100
m.CHUNK = 512

print("A moment of silence, please...")
with m as source:
    r.adjust_for_ambient_noise(source)
    print("Set minimum energy threshold to {}".format(r.energy_threshold))
    while True:
        print("Say something!")
        audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            print("You said " + r.recognize(audio))
        except LookupError:
            print("Oops! Didn't catch that")

```

Error message:

```
A moment of silence, please...
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Set minimum energy threshold to 350.037988116
Say something!
Got it! Now to recognize it...
You said hello testing testing
Say something!
Traceback (most recent call last):
  File "listen.py", line 14, in <module>
    audio = r.listen(source)
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 265, in listen
    buffer = source.stream.read(source.CHUNK)
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 564, in read
    return pa.read_stream(self._stream, num_frames)
IOError: [Errno Input overflowed] -9981
```

**Comment by Uberi** [comment] 2015-07-29 23:43
This seems to be caused by the script not being able to keep up with the audio input.

Try increasing the chunk size to boost the recognition speed:

```python
m = speech_recognition.Microphone()
m.CHUNK = 8192 # increased by a factor of 8
with m as source:
    pass # do the usual stuff here
```

**Comment by chaoming** [comment] 2015-07-30 05:23
Unfortunately I can't. If I set CHUNK to 1024, it will crash at starting. I think it is related to the small memory size Raspberry Pi has.

Do you think if I could lower the sample rate from 44100 to 8000, it might be a solution?

**Comment by Uberi** [comment] 2015-07-31 18:55
Might be worth trying. I will eventually give it a test on my RPi 2 and see how that goes.

**Comment by XayOn** [comment] 2015-08-29 00:56
I've just tried my RPI with this and 1024 as chunk size and goes smooth =/ 
What are you running on it?
Is dmesg saying anything about OOM?

**Comment by Uberi** [comment] 2015-08-30 06:17
Indeed, it works fine on my Raspberry Pi 2. I am using a sample rate of 16000 though, which is the current default value. Let us know if that works for you.

**Comment by jeremygray** [comment] 2015-09-08 15:27
I have a minimal example working from the python command prompt (google returns the correct text, given a .wav file). However, I get the same error number as the OP when trying the command-line super basic example:

    [jrg:~] jgray% python -m speech_recognition
    A moment of silence, please...
    Traceback (most recent call last):
      File "/Users/jgray/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/Users/jgray/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/Users/jgray/anaconda/lib/python2.7/site-packages/speech_recognition/__main__.py", line 9, in <module>
        r.adjust_for_ambient_noise(source)
      File "/Users/jgray/anaconda/lib/python2.7/site-packages/speech_recognition/__init__.py", line 248, in adjust_for_ambient_noise
        buffer = source.stream.read(source.CHUNK)
      File "/Users/jgray/anaconda/lib/python2.7/site-packages/pyaudio.py", line 605, in read
        return pa.read_stream(self._stream, num_frames)
    IOError: [Errno Input overflowed] -9981

**Comment by Uberi** [comment] 2015-09-08 20:42
Hi @jeremygray,

Have you tried lowering the sample rate? To do so, simply replace `Microphone()` with, for example, `Microphone(sample_rate=8000)`.

**Comment by felipenegriO** [comment] 2015-09-18 17:21
WOW! i need the answer! I'm Brazilian... Sorry if i don't write good.

I have a even problem, I already tested "Microphone(sample_rate=8000)",
"m = speech_recognition.Microphone()
m.CHUNK = 8192 # increased by a factor of 8
with m as source:
    pass # do the usual stuff here"
Anyway I need HELP! rs

**Comment by Uberi** [comment] 2015-09-18 17:36
Hi @felipenegriO,

What are the results of lowering the sample rate?

**Comment by chaoming** [comment] 2015-09-22 04:04
It seems my hardware wouldn't allow anything other than the default sample rate 44100. @Uberi how do you change the sample rate of your device? Sorry, I know this is a bit irrelevant to the project, but I am stuck. If I change the sample rate in the python script, pyaudio would give me an error: Invalid sample rate.

**Comment by Uberi** [comment] 2015-09-22 06:52
@chaoming, a 44.1k sample rate is too high for speech recognition purposes, so perhaps you should reconfigure your device to downsample or otherwise reduce the rate. The correct way to do this will depend on the audio device.

**Comment by felipenegriO** [comment] 2015-09-22 14:28
So, 
My result:


A moment of silence, please...
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
Set minimum energy threshold to 4905.3
Say something!
Got it! Now to recognize it...
You said teste som
Say something!
Traceback (most recent call last):
  File "reconhecer.py", line 16, in <module>
    audio = r.listen(source)
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 304, in listen
    buffer = source.stream.read(source.CHUNK)
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 564, in read
    return pa.read_stream(self._stream, num_frames)
IOError: [Errno Input overflowed] -9981

**Comment by Uberi** [comment] 2015-09-22 21:50
@felipenegriO, what was the modified code that resulted in that output?

**Comment by felipenegriO** [comment] 2015-09-22 22:35
I try sample_rate=16000 .. sample_rate=8000 .. 44100 .. 48000
I'm try modify __init__.py

this is my code:

#!/usr/bin/python
# -*- coding: UTF-8 -*-
import speech_recognition as sr
import os

r = sr.Recognizer()
m= sr.Microphone(sample_rate=16000)
print("A moment of silence, please...")
with m as source:
    pass
    r.adjust_for_ambient_noise(source)
    print(u"Set minimum energy threshold to {}".format(r.energy_threshold))
    while True:
        print("Say something!")
        audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            value = r.recognize_google(audio)
#            os.system("espeak -vpt-br -k -30".format(value))

            if str is bytes: # this version of Python uses bytes for string (Python 2)
                print(u"You said {}".format(value).encode("utf-8"))
            else: # this version of Python uses unicode for strings (Python 3+)
                print("You said {}".format(value))
        except sr.UnknownValueError:
            print("Oops! Didn't catch that")
        except LookupError:
            print("Oops! Didn't catch that")
        except IOError:
            print("Oops! Didn't catch that")

**Comment by felipenegriO** [comment] 2015-09-22 22:40
our buggy was kind !
#!/usr/bin/python

import speech_recognition as sr
import os

r = sr.Recognizer()
m= sr.Microphone(sample_rate=16000)
print("A moment of silence, please...")
with m as source:
    pass
    r.adjust_for_ambient_noise(source)
    print(u"Set minimum energy threshold to {}".format(r.energy_threshold))
    while True:
        print("Say something!")
        audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            value = r.recognize_google(audio)
            if str is bytes: # this version of Python uses bytes for string (Python 2)
                print(u"You said {}".format(value).encode("utf-8"))
            else: # this version of Python uses unicode for strings (Python 3+)
                print("You said {}".format(value))
        except sr.UnknownValueError:
            print("Oops! Didn't catch that")
        except LookupError:
            print("Oops! Didn't catch that")
        except IOError:
            print("Oops! Didn't catch that")

**Comment by felipenegriO** [comment] 2015-09-24 12:56
@Uberi Not Would not need to clean the " buffer " ?
in line 
File "/usr/local/lib/python2.7/dist-packages/speech_recognition/init.py", line 304, in listen
buffer = source.stream.read(source.CHUNK)

Because the ERROR indicates that?

IOError: [Errno Input overflowed] -9981

Or not?

I'm need help!

**Comment by felipenegriO** [comment] 2015-09-24 16:16
@Uberi  it's me again
I modified the following lines of the following files...
PyAudio.py - line 604
for this:
try:
           aux =  pa.read_stream(self._stream, num_frames) #this is line 604
        except IOError as ex:
           if ex[1] != pa.paInputOverflowed:
                raise
           aux = None   # or however you choose to handle it, e.g. return None
        return aux
and in __init__.py :
line 251
 buffer = source.stream.read(source.CHUNK)
 if not buffer:break
 if buffer: break

this is crazy however works...
too in line 278:
  if not buffer: break


 my problem is resolved


UHUU!

**Comment by Uberi** [comment] 2015-11-02 05:44
> October 18, 2015
> PyAudio 0.2.9 is a new release with bug fixes related to overflow error handling and IOError exception arguments.

This issue has now been fixed in PyAudio - please upgrade to PyAudio v0.2.9!

**Closed by Uberi** 2015-11-02 05:44 UTC

**Comment by nadavb** [comment] 2016-11-14 14:06
I upgraded to v0.2.9 and it still happens.. :(

**Comment by felipenegriO** [comment] 2016-11-15 00:02
What is the Error? Send me please!

2016-11-14 12:07 GMT-02:00 Nadav Bdfdf <notifications@github.com>:

**Comment by nadavb** [comment] 2016-11-15 07:09
The only way I managed to workaround this problem, is to use the callback approach, instead of using the blocking read operation.
