### ISSUE TITLE
Problem with google API

### ISSUE THREAD

**Issue by i3evelyn** [Uberi/speech_recognition#176] opened 2016-11-26 04:09 UTC
Hi, I encountered a problem. It's about google speech api.
------------------

1. I run the code just as the sample is. The input are audios 16k and mono. But only one audio can be accurately recognized, other inputs result in an error: recognition connection failed: **[error 32] Broken pipe**. For some inputs the error is **Bad gateway error**.

2. I thought problem1 might be due to the API key authorization problem. So I applied for an API key, but after I adding the value of key in [recognizer_instance.recognize_google(audio_data, **key ="****"**, language = "en-US", show_all = False)], it also results in a **Broken pipe error**. Even the only audio that works before encountered the same  problem.
3. So would you please show me what is the cause of this problem and how to solve it ?
Thank you so much!

System information
------------------

(Delete all the statements that don't apply.)

My **system** is "Ubuntu 16.04.2 ", 

My **Python version** is 2.7.

**Comment by Uberi** [comment] 2016-12-02 09:23
Hi @i3evelyn,

Without seeing the code/audio files, I couldn't really say what the issue is. I'll be closing this now, but feel free to re-open after posting your code and input audio.

**Closed by Uberi** 2016-12-02 09:23 UTC
