### ISSUE TITLE
Can't install pocketsphinx on windows

### ISSUE THREAD

**Issue by Jeff-Tian** [Uberi/speech_recognition#259] opened 2017-08-18 12:06 UTC
Steps to reproduce
------------------

1. Switch to speech_recognition folder
2. Run `pip3 install 
pocketsphinx-0.1.3-cp35-cp35m-win_amd64.whl`

Expected behaviour
------------------

Sphinx should be installed successfully

Actual behaviour
----------------
Error occurred:
pocketsphinx-0.1.3-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.
```
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

My **system** is <Windows 7 x64>.

My **Python version** is <3.6.2>. (You can check this by running `python -V`.)

My **Pip version** is <9.0.1>. (You can check this by running `pip -V`.)

My **SpeechRecognition library version** is <3.7.1>. (You can check this by running `python -c "import speech_recognition as sr;print(sr.__version__)"`.)

My **PyAudio library version** is <0.2.11> / I don't have PyAudio installed. (You can check this by running `python -c "import pyaudio as p;print(p.__version__)"`.)

I **installed PocketSphinx from** <this github repo thirdparty folder>. (For example, from the Debian repositories, from Homebrew, or from the source code.)

**Comment by neopedro** [comment] 2017-11-24 12:54
The problem is that you cannot install a python 3.5 lib on python 3.6 version, check out and download the correct version for you platform, https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by sujitvasanth** [comment] 2017-11-30 23:39
you can install pocketsphinx...this is now easy on windows from terminal with python idle 2,7,14:

cd c://python27/scripts
pip install --upgrade pip setuptools wheel
pip install --upgrade pocketsphinx

here's a simple example

import speech_recognition as sr; import time
def callback(recognizer, audio):
    try: print recognizer.recognize_sphinx(audio)
    except: return
m = sr.Microphone(); r = sr.Recognizer()
stop_listening = r.listen_in_background(m, callback)
while True: time.sleep(1)

**Comment by Uberi** [comment] 2017-12-05 09:31
Hi @Jeff-Tian,

It seems like you've got it working! I'll close this for now, but feel free to re-open if the issue persists. We will be upgrading bundled Pocketsphinx versions very soon.

**Closed by Uberi** 2017-12-05 09:31 UTC
