### ISSUE TITLE
Google Speech Recognition 

### ISSUE THREAD

**Issue by aditiranasaria** [Uberi/speech_recognition#230] opened 2017-05-08 11:14 UTC
Steps to reproduce
------------------
I was trying to run Google speech recognition API, but triggered the following section of the code

```
except sr.RequestError as e:
       print("Could not request results from Google Speech Recognition service; {0}".format(e))
```

Whenever size of audio file exceeds 1 MB. 

An error for "Bad Gateway" occurs-

"Could not request results from Google Speech Recognition service; recognition re
quest failed: Bad Gateway"

System information
------------------
My **system** is Windows 8 x64.

My **Python version** is 3.5. 

My **Pip version** is 9.0.1. 

My **SpeechRecognition library version** is 3.6.5.

My **PyAudio library version** is 0.2.11

**Comment by beeedy** [comment] 2017-05-09 16:24
Same issue here, however I am getting the error:
`Could not request results from Google Speech Recognition service; recognition request failed: Forbidden`

## System information

My **system** is OSX 0.12.4 (16E195)
My **Python** version is 2.7
My **SpeechRecognition** library version is 3.6.3
My **PyAudio** library version is

**Comment by r-a-o** [comment] 2017-05-26 11:28
@aditiranasaria 
I think your "Bad Gateway" error is a result of API reaching its limits. Take a look at their API limits:
https://cloud.google.com/speech/limits

It also states that:
"Audio longer than ~1 minute must use the uri field to reference an audio file in Google Cloud Storage"
meaning you will need to first push your audio file (which is longer than 1min) to G cloud before using it as source for the speech engine. 
I think this condition isn't currently being taken care of in this lib.

**Comment by Uberi** [comment] 2017-12-05 09:51
It seems like @r-a-o is right - the API limits are causing web request errors. I'll close this for now, but feel free to reopen if it seems like this isn't the root cause!

**Closed by Uberi** 2017-12-05 09:51 UTC
