### ISSUE TITLE
Cannot change the recognition language

### ISSUE THREAD

**Issue by swinkq** [Uberi/speech_recognition#86] opened 2016-02-26 15:21 UTC
## Steps to reproduce

I want to make google speech recognizing russian language. I  change this "en-US" to "ru" in recognize_google section, in **init**.py, but nothing happens, it still recognizing in English.
## Expected behaviour

I just want it to regonize russian language via google speech.
## Actual behaviour

But it still recognizing in english.
## System information

My **SpeechRecognition library version** is 3.1.3. 
My **PyAudio library version** is 0.2.8

**Comment by Uberi** [comment] 2016-02-27 04:36
Hi @swinq,

It sounds like you're editing the library source code so that it uses Russian. We can't really tell what the issue is without knowing how you edited the library.

Also, this is not necessary to use a different language. Simply use `r.recognize_google(audio, language="ru")` instead of `r.recognize_google(audio)`, and it will recognize using Russian. This is all well-documented in the [library reference](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instancerecognize_googleaudio_data-key--none-language--en-us-show_all--false).

If it's still not working, please post your code (or a stripped down version demonstrating the problem), and we can do some debugging on it. It is also very helpful to have audio samples that demonstrate the issue.

**Comment by Uberi** [comment] 2016-03-04 03:23
Unfortunately not at this time. In the future there may be support for grammars, but it needs some consideration to make it easy to install and use.

In the meantime, I recommend PocketSphinx, Kaldi, or SAPI (on Windows only) for this sort of task.

**Comment by i3evelyn** [comment] 2016-11-18 13:27
I use the code "r.recognize_google(audio, language="ch-ZN")", but neither get a bad gateway or "google cannot understand". Please help me!

**Comment by Uberi** [comment] 2016-11-21 08:52
Fixed in 3.5.0!

**Closed by Uberi** 2016-11-21 08:52 UTC
Labels: completed-for-release
