### ISSUE TITLE
Stream Closed Error

### ISSUE THREAD

**Issue by stevenrchun** [Uberi/speech_recognition#71] opened 2015-12-05 05:53 UTC
The library is awesome and, even as green as I am, I nearly have it working. I'm playing around with it in PyCharm but after one or two recordings, it gives me an error. This is my output.

```
A moment of silence, please...
2015-12-04 23:39:04.175 Python[40487:860874] 23:39:04.175 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Set minimum energy threshold to 74.0823600901
Say something!
Got it! Now to recognize it...
You said please
Say something!
Traceback (most recent call last):
  File "/Users/stevenchun/PycharmProjects/VoiceRecognition/speech_recognition/__main__.py", line 29, in <module>
    print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
  File "/Users/stevenchun/PycharmProjects/VoiceRecognition/speech_recognition/__init__.py", line 80, in __exit__
    if not self.stream.is_stopped():
  File "/usr/local/lib/python2.7/site-packages/pyaudio.py", line 543, in is_stopped
    return pa.is_stream_stopped(self._stream)
IOError: [Errno -9988] Stream closed
```

I downloaded this all today so I have the most recent version as well as the most recent version of PyAudio. I haven't changed `main` at all, but here it is anyway:

```
import speech_recognition as sr

r = sr.Recognizer()
m = sr.Microphone()

try:
    print("A moment of silence, please...")
    with m as source:
        r.adjust_for_ambient_noise(source)
        print("Set minimum energy threshold to {}".format(r.energy_threshold))
        while True:
            print("Say something!")
            audio = r.listen(source)
            print("Got it! Now to recognize it...")
            try:
                # recognize speech using Google Speech Recognition
                value = r.recognize_google(audio)
                # we need some special handling here to correctly print unicode characters to standard output
                if str is bytes: # this version of Python uses bytes for strings (Python 2)
                    print(u"You said {}".format(value).encode("utf-8"))

                else: # this version of Python uses unicode for strings (Python 3+)
                    print("You said {}".format(value))

            except sr.UnknownValueError:
                print("Oops! Didn't catch that")
            except sr.RequestError as e:
                print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))

except KeyboardInterrupt:
    pass
```

At first I thought the program was trying to access Google Speech too rapidly (more than once per second as is allowed), but putting in `time.sleep(1)` didn't work.

Any ideas?
Thanks a bunch

**Comment by Uberi** [comment] 2015-12-06 02:06
Hi @Waffls,

* What OS/OS version are you running?
* Are you able to use any of the PyAudio sample scripts? For example, [this one](https://gist.github.com/mabdrabo/8678538).
* Does `arecord` work for recording audio?

I've noticed this issue occurring for several people, and so far all that seems to be common between them is that they're running OS X with the latest PyAudio version, which makes reproduction rather problematic.

**Comment by Waffls** [comment] 2015-12-06 04:39
Hey @Uberi ,

* I'm running OS X with the latest PyAudio, so should I try to downgrade to a previous PyAudio? If so, how would I do that (again, I'm pretty much a total novice)
* Yup, that sample script worked fine as long as I set CHANNELS to 1. Otherwise, I got this error
```python
Traceback (most recent call last):
  File "/Users/stevenchun/PycharmProjects/VoiceRecognition/speech_recognition/sound_recorder.py", line 17, in <module>
    frames_per_buffer=CHUNK)
  File "/usr/local/lib/python2.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9998] Invalid number of channels
```
* Sorry, but what's `arecord`? Did you mean the `record` function? I'm fairly sure it works. I replaced `listen` with `record` in `main` and set `duration` for 5 seconds so `main` looks like this
```python
__author__ = 'stevenchun'
import speech_recognition as sr

r = sr.Recognizer()
m = sr.Microphone()

try:
    print("A moment of silence, please...")
    with m as source:
        r.adjust_for_ambient_noise(source)
        print("Set minimum energy threshold to {}".format(r.energy_threshold))
        while True:
            print("Say something!")
            audio = r.record(source, 5) #Here's where I made the change
            print("Got it! Now to recognize it...")
            try:
                # recognize speech using Google Speech Recognition
                value = r.recognize_google(audio)
                # we need some special handling here to correctly print unicode characters to standard output
                #I have python 2 so this is the one I'm probably using
                if str is bytes: # this version of Python uses bytes for strings (Python 2)
                    print(u"You said {}".format(value).encode("utf-8"))

                else: # this version of Python uses unicode for strings (Python 3+)
                    print("You said {}".format(value))

            except sr.UnknownValueError:
                print("Oops! Didn't catch that")
            except sr.RequestError as e:
                print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))

except KeyboardInterrupt:
    pass
```
When I ran that, it recorded the audio just fine, google translated it just fine, and then it crashed with the same error.
```python
/usr/local/bin/python /Users/stevenchun/PycharmProjects/VoiceRecognition/speech_recognition/record_test2.py
A moment of silence, please...
2015-12-05 22:31:08.272 Python[41273:1030179] 22:31:08.271 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Set minimum energy threshold to 143.833006091
Say something!
Got it! Now to recognize it...
You said hello hello hello
Say something!
Traceback (most recent call last):
  File "/Users/stevenchun/PycharmProjects/VoiceRecognition/speech_recognition/record_test2.py", line 30, in <module>
    print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
  File "/Users/stevenchun/PycharmProjects/VoiceRecognition/speech_recognition/__init__.py", line 80, in __exit__
    if not self.stream.is_stopped():
  File "/usr/local/lib/python2.7/site-packages/pyaudio.py", line 543, in is_stopped
    return pa.is_stream_stopped(self._stream)
IOError: [Errno -9988] Stream closed
```
I plan on transferring this all to an old Rasberry PI and using it with Wolfram Alpha's API to make a question answering bot, so maybe that will help with the OS X issue. Thanks so much for helping!

**Comment by LovelyHorse** [comment] 2015-12-06 06:18
I remember having similar issues, ended up switching to python 3.5 and relevant PyAudio, using listen_in_background and they resolved. Not too much I can offer in the way of guidance. 

I recommend using PyCharm if you aren't already. Set a debug point just at __exit__ in init Microphone() in __init__ and walk through the program flow step by step (tapping f7) to see if you notice any irregularities closing your microphone object.

**Comment by Waffls** [comment] 2015-12-10 07:53
Hey @LovelyHorse, 

Does the library still run in Python 3.5? Is there any conversion necessary? I understand there's no backwards compatibility.

Also, what did using `listen_in_background()` do? And what is the `callback` parameter??

**Comment by Uberi** [comment] 2015-12-10 09:45
Hi @Waffls,

The library is fully compatible with Python 2.6, 2.7, and 3.3+ with no conversion necessary.

Please see the documentation for `listen_in_background`, it's in the README! I can't imagine why it might help with the issue, however, since internally they use the exact same mechanism.

It might be worth trying [this workaround](https://github.com/Uberi/speech_recognition/issues/70#issuecomment-162291982) on #70 and seeing if that helps - basically changing the sample rate to 48k.

I plan on adding proper sample rate detection, so if that is the issue then the workaround will not be necessary in the next version.

**Comment by Waffls** [comment] 2015-12-19 05:46
I tried changing the chunks and sample rate, neither worked to fix the issue. I tried running it on my Raspberry PI first in Python 2 with PyAudio 2.8 and it kept giving me a `Stream Overflowed` error right off the bat after the energy levels were detected. I updated to Python 3 with PyAudio 2.9, changed the chunks to 2048 (I don't understand what chunks are but this helped), set sample rate to 8000, and now I can perform one voice recognition (and voice answer through Wolfram Alpha and IVONA) before getting both a `stream overflowed ` error AND a `Stream Closed` error. 

Again here is the script I'm running. An alteration of __main__

```python
__author__ = 'stevenchun'
import speech_recognition as sr
from wolfram_class import *
import pyvona
import pyglet
#import pygame

appid = "E2Y6RV-XGKX42EXAY"

r = sr.Recognizer()
m = sr.Microphone()
m.SAMPLE_RATE = 48000

# this is a ugly little function I had to write to use pyglet properly. On my raspberry PI I use pygame
# and it's much better. This kept giving me an error about how many arguments "exiter" was taking until I just gave 
# it a random argument to take. But at least it works.
def exiter(dt):
    pyglet.app.exit()

print("A moment of silence, please...")
with m as source:
    r.adjust_for_ambient_noise(source)
    print("Set minimum energy threshold to {}".format(r.energy_threshold))
    # create the IVONA voice
    winston = pyvona.create_voice("GDNAJRUJP55AJ25DGUPA", "MXlt+SAWMs6ZUE4rRmq2e8LbhWIISuBpuJmi5sWV")
    winston.codec = "mp3"
    print winston.codec
    while True:
        print("Say something!")
        audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            # recognize speech using Google Speech Recognition
            value = r.recognize_google(audio)

            #we need some special handling here to correctly print unicode characters to standard output
            #I have python 2 so this is the one I'm probably using

            if str is bytes: # this version of Python uses bytes for strings (Python 2)
                # instead of printing value, store it, and send it over to wolfram alpha
                value = value.encode("utf-8")
                print value
                #get the answer from Wolfram's returned XML document. The implementation of this is
                #hideous. I don't even know what an XML is. I just kept on iterating mannn.
                answer = ask_wolfram(value, appid)

                #creates an audio.mp3 file storing the audio of IVONA saying the answer
                winston.fetch_voice(answer, "audio.mp3")

                #plays the audio. Uuuuuugly. 
                speech = pyglet.media.load("audio.mp3", streaming = False)
                speech.play()

                pyglet.clock.schedule_once(exiter, speech.duration)
                pyglet.app.run()


            else: # this version of Python uses unicode for strings (Python 3+)
                print("You said {}".format(value))

        except sr.UnknownValueError:
            print("Oops! Didn't catch that")
        except sr.RequestError as e:
            print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
```

And the error:

```python
Traceback (most recent call last):
  File "/Users/stevenchun/PycharmProjects/VoiceRecognition/tests/full_test.py", line 64, in <module>
    print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
  File "/Users/stevenchun/PycharmProjects/VoiceRecognition/speech_recognition/__init__.py", line 80, in __exit__
    if not self.stream.is_stopped():
  File "/usr/local/lib/python2.7/site-packages/pyaudio.py", line 543, in is_stopped
    return pa.is_stream_stopped(self._stream)
IOError: [Errno -9988] Stream closed
```
I am at a loss for what to do. Halp.

**Comment by kpfromer** [comment] 2016-02-02 15:12
I have been getting the same error!

**Comment by Uberi** [comment] 2016-02-04 05:57
I think I have a rough idea of what's going wrong now. Can you try this version of your code?

```python
import speech_recognition as sr

r = sr.Recognizer()
m = sr.Microphone()

try:
    print("A moment of silence, please...")
    with m as source: r.adjust_for_ambient_noise(source)
    print("Set minimum energy threshold to {}".format(r.energy_threshold))
    while True:
        print("Say something!")
        with m as source: audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            # recognize speech using Google Speech Recognition
            value = r.recognize_google(audio)

            # we need some special handling here to correctly print unicode characters to standard output
            if str is bytes: # this version of Python uses bytes for strings (Python 2)
                print(u"You said {}".format(value).encode("utf-8"))
            else: # this version of Python uses unicode for strings (Python 3+)
                print("You said {}".format(value))
        except sr.UnknownValueError:
            print("Oops! Didn't catch that")
        except sr.RequestError as e:
            print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
except KeyboardInterrupt:
    pass
```

**Comment by garciapablo** [comment] 2016-02-04 21:54
I quickly scanned this but most of the API's tend to have a size limit. I was getting that issue with the reconize att API, having to reduce it from 4 to 1 minute. Not sure how big file size you are passing but that is one issue. The second thing is that, Google limits how many calls you can make to it's API per day.

**Comment by DarkmatterVale** [comment] 2016-02-09 21:37
I am also getting this error running Mac OS X version 10.10.5. I have the most recent SpeechRecognition library and the most recent PyAudio library installed.

Any ideas @Uberi ?

**Comment by Uberi** [comment] 2016-02-10 04:39
@DarkmatterVale, your sample code gives a syntax error when attempting to run it. Have you tried the most recent code snippet I posted above?

**Comment by augustinek491** [comment] 2016-02-11 02:05
Using PyAudio v 0.2.9 and Speech Recognition v 3.2 on Raspberry Pi B running Raspian. I get the same error "IOError: [Errno -9988] Stream closed" when I attempt background listening. Any advice?

**Comment by Uberi** [comment] 2016-02-11 04:24
@augustinek491, have you tried the [most recent code snippet](https://github.com/Uberi/speech_recognition/issues/71#issuecomment-179660804) I posted above?

**Comment by augustinek491** [comment] 2016-02-11 13:31
@Uberi ,Thanks a lot for the help, I tried the most recent code snippet above:

Good News:
* Program no longer crashes, no more errors. 1st iteration works fine

Bad News:
* Successfully recognises voice commands for only 2 to 4 iterations.
* Afterwards tends to recognise background noise (when user is silent) as speech. leading to erroneous results most of the time. 

Could it be the microphone since I'm using a cheap one (£5)? Any thoughts?

**Comment by Uberi** [comment] 2016-02-20 21:25
Hi @augustinek491, just saw your reply.

To eliminate some possible causes of this, can you try the following snippet?

```python
import speech_recognition as sr

r = sr.Recognizer()
m = sr.Microphone()

try:
    print("A moment of silence, please...")
    while True:
        with m as source: r.adjust_for_ambient_noise(source)
        print("Set minimum energy threshold to {}".format(r.energy_threshold))
        print("Say something!")
        with m as source: audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            # recognize speech using Google Speech Recognition
            value = r.recognize_google(audio)

            # we need some special handling here to correctly print unicode characters to standard output
            if str is bytes: # this version of Python uses bytes for strings (Python 2)
                print(u"You said {}".format(value).encode("utf-8"))
            else: # this version of Python uses unicode for strings (Python 3+)
                print("You said {}".format(value))
        except sr.UnknownValueError:
            print("Oops! Didn't catch that")
        except sr.RequestError as e:
            print("Uh oh! Couldn't request results from Google Speech Recognition service; {0}".format(e))
except KeyboardInterrupt:
    pass
```

Also, can you post the full output of running the above?

**Comment by MrRuela** [comment] 2017-01-27 13:50
The library is awesome but I am having the same problem with it (IOError: [Errno -9988] Stream closed).
I have the latest versions of pyaudio and of this library installed. Running on python 2.7 on macOS.

**Comment by MrRuela** [comment] 2017-01-27 15:09
I am running version 3.6 on macOS sierra and it works perfectly now. Great job Uberi! Thank you very much.

**Comment by Uberi** [comment] 2017-12-05 10:47
Since the original issue has been fixed in recent versions of PyAudio, I'll close this issue now - feel free to reopen if it persists!

**Closed by Uberi** 2017-12-05 10:47 UTC
