### ISSUE TITLE
ValueError: Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format

### ISSUE THREAD

**Issue by connect2robiul** [Uberi/speech_recognition#325] opened 2018-02-14 19:35 UTC
code 

```
import speech_recognition as sr
r = sr.Recognizer()
with sr.AudioFile("test.wav") as source:
    audio = r.record(source)

try:
    s = r.recognize_google(audio)
    print("Text: "+s)
except Exception as e:
    print("Exception: "+str(e))
```

error 

```
Traceback (most recent call last):
  File "/Users/robiulislam/anaconda3/lib/python3.6/site-packages/speech_recognition/__init__.py", line 203, in __enter__
    self.audio_reader = wave.open(self.filename_or_fileobject, "rb")
  File "/Users/robiulislam/anaconda3/lib/python3.6/wave.py", line 499, in open
    return Wave_read(f)
  File "/Users/robiulislam/anaconda3/lib/python3.6/wave.py", line 163, in __init__
    self.initfp(f)
  File "/Users/robiulislam/anaconda3/lib/python3.6/wave.py", line 143, in initfp
    self._read_fmt_chunk(chunk)
  File "/Users/robiulislam/anaconda3/lib/python3.6/wave.py", line 260, in _read_fmt_chunk
    raise Error('unknown format: %r' % (wFormatTag,))
wave.Error: unknown format: 65534

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/robiulislam/anaconda3/lib/python3.6/site-packages/speech_recognition/__init__.py", line 208, in __enter__
    self.audio_reader = aifc.open(self.filename_or_fileobject, "rb")
  File "/Users/robiulislam/anaconda3/lib/python3.6/aifc.py", line 912, in open
    return Aifc_read(f)
  File "/Users/robiulislam/anaconda3/lib/python3.6/aifc.py", line 351, in __init__
    self.initfp(file_object)
  File "/Users/robiulislam/anaconda3/lib/python3.6/aifc.py", line 316, in initfp
    raise Error('file does not start with FORM id')
aifc.Error: file does not start with FORM id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/robiulislam/anaconda3/lib/python3.6/site-packages/speech_recognition/__init__.py", line 234, in __enter__
    self.audio_reader = aifc.open(aiff_file, "rb")
  File "/Users/robiulislam/anaconda3/lib/python3.6/aifc.py", line 912, in open
    return Aifc_read(f)
  File "/Users/robiulislam/anaconda3/lib/python3.6/aifc.py", line 357, in __init__
    self.initfp(f)
  File "/Users/robiulislam/anaconda3/lib/python3.6/aifc.py", line 314, in initfp
    chunk = Chunk(file)
  File "/Users/robiulislam/anaconda3/lib/python3.6/chunk.py", line 63, in __init__
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 21, in <module>
    with sr.AudioFile("test.wav") as source:
  File "/Users/robiulislam/anaconda3/lib/python3.6/site-packages/speech_recognition/__init__.py", line 236, in __enter__
    raise ValueError("Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format")
ValueError: Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format
```

operating system is Mac & python version 3

**Comment by KarlClinckspoor** [comment] 2018-02-25 18:10
I had the same error when trying to open the "english.wav" file that was supplied in the examples. VLC didn't reproduce anything. Then I got a small part of a podcast with very clear english, and it worked. Did you try with other .wav files to see if the problem persists?

**Comment by connect2robiul** [comment] 2018-02-26 05:28
I download a clear sound video from YouTube and separated music from it.

**Comment by egoens** [comment] 2018-03-09 18:56
I'm getting the same issue. I've tried converting a file type (both an aac and and m4a) file to a wav format and I see this error. My conversion attempt has been through both ffmpeg and via iTunes. Each result is the same.

**Comment by BrendanCarlin** [comment] 2018-03-26 03:36
I’m not sure this is an issue with the code as much as it is the file you are using.  The error states it’s looking for a PCM WAV (or other alternative).  PCM is one of many ways to encode a WAV file.  The files that aren’t working for you must likely need to be encoded differently.

Check out the section titled “Comparison of coding schemes” on this wiki entry for wav files for additional details: 

https://en.m.wikipedia.org/wiki/WAV

Here’s a quick excerpt from that section:

“Audio in WAV files can be encoded in a variety of audio coding formats, such as GSM or MP3, to reduce the file size.

This is a reference to compare the monophonic (not stereophonic) audio quality and compression bitrates of audio coding formats available for WAV files including PCM, ADPCM, Microsoft GSM 06.10, CELP, SBC, Truespeech and MPEG Layer-3.”

**Comment by jocago** [comment] 2018-07-22 03:12
I'm having the same issue with an aiff file and a pcm/wav version I transcoded as a test.

**Comment by rskrebelis** [comment] 2018-09-06 08:07
Hi, for info- for me the problem was that file had single channel (mono), changing audio to stereo fixed issue for me.

**Comment by Mchighlight** [comment] 2018-10-08 14:54
> I'm getting the same issue. I've tried converting a file type (both an aac and and m4a) file to a wav format and I see this error. My conversion attempt has been through both ffmpeg and via iTunes. Each result is the same.
> 
> Also on Mac & python3

Hi! Can you convert the m4a file to wav file using the python codes. I tried to find a package that can convert the m4a file to a wav format . Without using the outer program such as iTunes or some Online Audio Converting Website

**Comment by partounian** [comment] 2018-10-18 23:10
I'm having this issue on a python 3.6 alpine container., anyone figured it out?

**Comment by clalanliu** [comment] 2018-10-26 09:52
I think you can just read your file first and time your data (in float32) with 32767 then reconstruct a PCM wav file :)

**Comment by Mchighlight** [comment] 2018-10-26 15:38
One way i tried is using the ffmpeg an covert it to wav format

**Comment by partounian** [comment] 2018-10-26 16:19
I'm an idiot. It was an MP3 file, just used pydub to convert.

**Comment by palikar** [comment] 2018-11-27 00:08
As @BrendanCarlin  said, this seemed to be a problem with the files that are being used. Maybe they are somehow corrupted. Even if this is not the case, the stack trace shows that the error comes from the wave.py library so it is not really an issue with the speech_recognition's code. Closing the issue for now but feel free to post solution/suggestion/question if you can't get it to work.

**Closed by palikar** 2018-11-27 00:08 UTC

**Comment by balaji2v** [comment] 2019-07-29 07:05
I'm facing this issue, Which fix worked finally? Can someone help?

**Comment by Sphinxs** [comment] 2019-11-23 19:31
Did someone fixed it?

**Comment by es234r** [comment] 2019-12-27 11:12
I fixed it
You got the same problem if youre using python 3.7 and above
if you use python 3.6 you can run the code

**Comment by icaijy** [comment] 2020-03-05 06:35
My python3.8.1 got the same problem

**Comment by arnab31399** [comment] 2020-07-07 14:25
> I fixed it
> You got the same problem if youre using python 3.7 and above
> if you use python 3.6 you can run the code

hello, please can you explain how to solve, I am using Python 3.6.... What r the steps taken by you to fix it???

**Comment by Sphinxs** [comment] 2020-07-24 16:20
Here's my solution:

```python
def convert_audio(path: str = None,
                  convert: str = 'wav',
                  stream: BufferedReader = None) -> dict:
    '''
        Convert MP3, OGG, FLV, WMA, ACC and MP4 audio / video files to WAV
        audio file, by default, or any file type supported by FFmpeg
        
        :param str path: Path to a MP3, OGG, FLV, WMA, ACC or MP4 audio /
         video file

        :param str convert: Type to convert the input file to

        :param BufferedReader stream: Stream file

        :rtype: Dict
        
        :raises FileNotFoundError: Audio was not found
    '''
    error_message = None

    try:
        _audio = AudioSegment.from_file_using_temporary_files(stream) \
            if stream else AudioSegment.from_file(path)
    except FileNotFoundError as error:
        error_message = 'Audio file was not found (convert audio)'

        logging.exception(error_message)

        return dict(error=error_message)
    except Exception as error:
        error_message = 'Unexpected error when open audio file (convert audio)'

        logging.exception(error_message)

        return dict(error=error_message)

    audio_converted = _audio.export(format=convert)

    audio_converted.seek(0)

    return dict(
        audio=_audio,
        audio_converted=audio_converted,
        error=error_message
    )


def audio(path: str = None,
          stream: BufferedReader = None) -> dict:
    '''
        Extract text from MP3, OGG, FLV, WMA, ACC, MP4 and WAV audio /
        video files, through Sphinx API
        
        :param str path: Path to an audio / video file
        
        :param BufferedReader stream: Stream file
        
        :rtype: Dict
        
        :raises FileNotFoundError: Audio was not found
    '''
    # If an error is issued at the Pocket Sphinx installation, remove the
    # `apt remove swig`, install the `apt install swig3.0` and create
    # a symbolic link `ln -s /usr/bin/swig3.0 /usr/bin/swig` to the new
    # version
    recognizer = speech_recognition.Recognizer()

    error_message = None

    try:
        _ = convert_audio(
            stream=stream) if stream else convert_audio(path=path)

        if _.get('error'):
            error_message = _.get('error')

            logging.exception(error_message)

            return dict(error=error_message)

        _audio = _.get('audio_converted')

        with speech_recognition.AudioFile(_audio) as file:
            _audio = recognizer.record(file)
    except FileNotFoundError as error:
        error_message = 'Audio file was not found (audio)'

        logging.exception(error_message)

        return dict(error=error_message)
    except Exception as error:
        error_message = 'Unexpected error when open audio file (audio)'

        logging.exception(error_message)

        return dict(error=error_message)

    text_sphinx = recognizer.recognize_sphinx(_audio)

    return dict(
        text=text_sphinx,
        error=error_message
    )
```

**Comment by yangdongchao** [comment] 2020-07-29 14:18
> Here's my solution:
> 
> ```python
> def convert_audio(path: str = None,
>                   convert: str = 'wav',
>                   stream: BufferedReader = None) -> dict:
>     '''
>         Convert MP3, OGG, FLV, WMA, ACC and MP4 audio / video files to WAV
>         audio file, by default, or any file type supported by FFmpeg
>         
>         :param str path: Path to a MP3, OGG, FLV, WMA, ACC or MP4 audio /
>          video file
> 
>         :param str convert: Type to convert the input file to
> 
>         :param BufferedReader stream: Stream file
> 
>         :rtype: Dict
>         
>         :raises FileNotFoundError: Audio was not found
>     '''
>     error_message = None
> 
>     try:
>         _audio = AudioSegment.from_file_using_temporary_files(stream) \
>             if stream else AudioSegment.from_file(path)
>     except FileNotFoundError as error:
>         error_message = 'Audio file was not found (convert audio)'
> 
>         logging.exception(error_message)
> 
>         return dict(error=error_message)
>     except Exception as error:
>         error_message = 'Unexpected error when open audio file (convert audio)'
> 
>         logging.exception(error_message)
> 
>         return dict(error=error_message)
> 
>     audio_converted = _audio.export(format=convert)
> 
>     audio_converted.seek(0)
> 
>     return dict(
>         audio=_audio,
>         audio_converted=audio_converted,
>         error=error_message
>     )
> 
> 
> def audio(path: str = None,
>           stream: BufferedReader = None) -> dict:
>     '''
>         Extract text from MP3, OGG, FLV, WMA, ACC, MP4 and WAV audio /
>         video files, through Sphinx API
>         
>         :param str path: Path to an audio / video file
>         
>         :param BufferedReader stream: Stream file
>         
>         :rtype: Dict
>         
>         :raises FileNotFoundError: Audio was not found
>     '''
>     # If an error is issued at the Pocket Sphinx installation, remove the
>     # `apt remove swig`, install the `apt install swig3.0` and create
>     # a symbolic link `ln -s /usr/bin/swig3.0 /usr/bin/swig` to the new
>     # version
>     recognizer = speech_recognition.Recognizer()
> 
>     error_message = None
> 
>     try:
>         _ = convert_audio(
>             stream=stream) if stream else convert_audio(path=path)
> 
>         if _.get('error'):
>             error_message = _.get('error')
> 
>             logging.exception(error_message)
> 
>             return dict(error=error_message)
> 
>         _audio = _.get('audio_converted')
> 
>         with speech_recognition.AudioFile(_audio) as file:
>             _audio = recognizer.record(file)
>     except FileNotFoundError as error:
>         error_message = 'Audio file was not found (audio)'
> 
>         logging.exception(error_message)
> 
>         return dict(error=error_message)
>     except Exception as error:
>         error_message = 'Unexpected error when open audio file (audio)'
> 
>         logging.exception(error_message)
> 
>         return dict(error=error_message)
> 
>     text_sphinx = recognizer.recognize_sphinx(_audio)
> 
>     return dict(
>         text=text_sphinx,
>         error=error_message
>     )
> ```
when i run your code , i find some mistake about "stream: BufferedReader = None" .NameError: name 'BufferedReader' is not defined. so i want to ask what is "BufferedReader",i can not find some useful imformation on network,can you tell me why?
thanks.

**Comment by Sphinxs** [comment] 2020-07-29 17:17
```python
from io import BufferedReader
```

**Comment by yangdongchao** [comment] 2020-07-30 01:51
> ```python
> from io import BufferedReader
> ```

thank your reply.
but i can not run this code. 
`# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""
from io import BufferedReader
import speech_recognition
import logging
from pydub import AudioSegment
def convert_audio(path: str = None,
                  convert: str = 'wav',
                  stream: BufferedReader = None) -> dict:
    '''
        Convert MP3, OGG, FLV, WMA, ACC and MP4 audio / video files to WAV
        audio file, by default, or any file type supported by FFmpeg
        
        :param str path: Path to a MP3, OGG, FLV, WMA, ACC or MP4 audio /
         video file

        :param str convert: Type to convert the input file to

        :param BufferedReader stream: Stream file

        :rtype: Dict
        
        :raises FileNotFoundError: Audio was not found
    '''
    error_message = None

    try:
        _audio = AudioSegment.from_file_using_temporary_files(stream) \
            if stream else AudioSegment.from_file(path)
    except FileNotFoundError as error:
        error_message = 'Audio file was not found (convert audio)'

        logging.exception(error_message)

        return dict(error=error_message)
    except Exception as error:
        error_message = 'Unexpected error when open audio file (convert audio)'

        logging.exception(error_message)

        return dict(error=error_message)

    audio_converted = _audio.export(format=convert)

    audio_converted.seek(0)

    return dict(
        audio=_audio,
        audio_converted=audio_converted,
        error=error_message
    )


def audio(path: str = None,
          stream: BufferedReader = None) -> dict:
    '''
        Extract text from MP3, OGG, FLV, WMA, ACC, MP4 and WAV audio /
        video files, through Sphinx API
        
        :param str path: Path to an audio / video file
        
        :param BufferedReader stream: Stream file
        
        :rtype: Dict
        
        :raises FileNotFoundError: Audio was not found
    '''
    # If an error is issued at the Pocket Sphinx installation, remove the
    # `apt remove swig`, install the `apt install swig3.0` and create
    # a symbolic link `ln -s /usr/bin/swig3.0 /usr/bin/swig` to the new
    # version
    recognizer = speech_recognition.Recognizer()

    error_message = None

    try:
        _ = convert_audio(
            stream=stream) if stream else convert_audio(path=path)

        if _.get('error'):
            error_message = _.get('error')

            logging.exception(error_message)

            return dict(error=error_message)

        _audio = _.get('audio_converted')

        with speech_recognition.AudioFile(_audio) as file:
            _audio = recognizer.record(file)
    except FileNotFoundError as error:
        error_message = 'Audio file was not found (audio)'

        logging.exception(error_message)

        return dict(error=error_message)
    except Exception as error:
        error_message = 'Unexpected error when open audio file (audio)'

        logging.exception(error_message)

        return dict(error=error_message)

    text_sphinx = recognizer.recognize_sphinx(_audio)

    return dict(
        text=text_sphinx,
        error=error_message
    )
    
dct=audio("2-1.wav")
#print(dct['text'])`

this is my code, when i run this code ,i get following error

`ERROR:root:Audio file was not found (convert audio)
Traceback (most recent call last):
  File "C:/Users/ydc/.spyder-py3/temp.py", line 33, in convert_audio
    if stream else AudioSegment.from_file(path)
  File "H:\anaconda\lib\site-packages\pydub\audio_segment.py", line 622, in from_file
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "H:\anaconda\lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '2-1.wav'
ERROR:root:Audio file was not found (convert audio)
NoneType: None
`
I'm sure this file（2-1.wav） is in the same directory as the Python file.
Can you share your complete code? Or give me some suggestions to solve this error.

**Comment by VernadskyDanya** [comment] 2021-07-01 10:18
These manipulations helped me to **restore** the .**wav** file and the script work!

```
import soundfile
data, samplerate = soundfile.read('old.wav')
soundfile.write('new.wav', data, samplerate, subtype='PCM_16')
```

**Comment by Shivachauhan17** [comment] 2023-03-19 13:45
* example
```ruby
import sounddevice as sd 
from scipy.io.wavfile import write
import numpy as np

freq = 44100
duration=10
print("speak")
recording = sd.rec(int(duration * freq), samplerate=freq, channels=2)
sd.wait()
# before saving make all integers in array 32 bit      
y = (np.iinfo(np.int32).max * (recording/np.abs(recording).max())).astype(np.int32)
write("recording0.wav", freq, y)

print("successfully recorded") 
```
that worked for me

**Comment by ttkrpink** [comment] 2024-03-09 12:12
> ```ruby
> import sounddevice as sd 
> from scipy.io.wavfile import write
> import numpy as np
> 
> freq = 44100
> duration=10
> print("speak")
> recording = sd.rec(int(duration * freq), samplerate=freq, channels=2)
> sd.wait()
> # before saving make all integers in array 32 bit      
> y = (np.iinfo(np.int32).max * (recording/np.abs(recording).max())).astype(np.int32)
> write("recording0.wav", freq, y)
> 
> print("successfully recorded") 
> ```

Where do I put the old audio file if the output of the above code can solve the problem?
