### ISSUE TITLE
wit.ai backend

### ISSUE THREAD

**Issue by maverickagm** [Uberi/speech_recognition#50] opened 2015-07-28 03:37 UTC
Hi. I've patched your module to be able to use the wit.ai engine as a backend instead of google. If you're interested in integrating this into your project the patch is here:
https://gist.github.com/maverickagm/56ee25f830ac4440cc70

To switch to the wit.ai backend you must specify stt_engine as 'wit' and provide a valid key:
r = sr.Recognizer()
r.stt_engine = 'wit'
r.key = 'my_wit_api_key_here'

In the recognize_wit() function, the show_all variable now toggles whether just the recognized text is returned to the entire json object (including entities)

Thanks.

**Comment by TheAtomicNord** [comment] 2015-08-27 05:50
This is amazing! I'd love to use this if you don't mind, but I'm not sure how to apply this patch to the SpeechRecognition module. 

I'd really appreciate some help if you have the time! Thanks.

**Comment by Uberi** [comment] 2015-08-30 06:23
I totally missed this one earlier, great work! This will be integrated in the next major release.

**Comment by Uberi** [comment] 2015-09-01 09:56
Added as part of v3.0.0!

**Closed by Uberi** 2015-09-01 09:56 UTC

**Comment by TheAtomicNord** [comment] 2015-09-08 08:16
Awesome! The wit.ai backend works perfectly as of 3.1. However, I'm having a bit of trouble getting exactly what I need from the response. For example, if I need just the intent of what is being said. I would really love some help. Thanks!

**Comment by Uberi** [comment] 2015-09-08 18:27
Hi @TheAtomicNord,

Try `sr.recognize_wit(audio, show_all=True)` - the `show_all` option will return the raw response from Wit.ai, which will contain the intent info.

**Comment by TheAtomicNord** [comment] 2015-09-08 21:54
Thanks @Uberi, but I've got that part down. The problem is when I just want the intent. The ```show_all``` option returns far more data than I need. Again, thanks for any help you can provide!

**Comment by Uberi** [comment] 2015-09-09 01:22
Ah, you can drill down in the response object since it's a JSON dictionary. Here's the [response format](https://wit.ai/docs/http/20141022#get-intent-via-text-link)!

Basically, the library does not modify the response object in `show_all` mode. The intents should be in there.

**Comment by TheAtomicNord** [comment] 2015-09-21 06:48
@Uberi 
Hey sorry to keep bothering you, but I really can't seem to figure this out. I'm a fairly novice programmer as you can probably tell. I need to get each part of the "Outcomes" list into a separate variable and python just isn't cooperating with me. 
Thanks again for all the help!

**Comment by Uberi** [comment] 2015-09-21 14:38
Hi @TheAtomicNord,

No worries, you can do so as follows:

```python
result = some_SOME_RECOGNIZER.recognize_wit(SOME_AUDIO_DATA, SOME_KEY, show_all=True)
outcomes = result["outcomes"]
first_outcome = outcomes[0] # you can also say first_outcome = result["outcomes"][0]` here
```

Note that there aren't necessarily any outcomes - if you just say something random, `outcomes` will be an empty list and accessing `outcomes[0]` will result in an error. Make sure to check how many outcomes there are before accessing them. Here's a complete example:

```python
import sys

import speech_recognition as sr

WIT_AI_KEY = "INSERT WIT.AI API KEY HERE" # Wit.ai keys are 32-character uppercase alphanumeric strings

# obtain audio from the microphone
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)

# recognize speech using Wit.ai
try:
    result = r.recognize_wit(audio, key=WIT_AI_KEY, show_all=True)
except sr.RequestError:
    print("Could not request results from Wit.ai service")
    sys.exit(1)

for outcome in result["outcomes"]:
    print("Intent:", outcome["intent"])
```

**Comment by TheAtomicNord** [comment] 2015-09-21 19:05
@Uberi 
You are truly a beautiful human being. Thank you so much for making my life easier and supporting this awesome module! Can't wait for 4.0!
