### ISSUE TITLE
AttributeError: Could not find PyAudio; check installation

### ISSUE THREAD

**Issue by sanster9292** [Uberi/speech_recognition#235] opened 2017-06-03 04:07 UTC
Steps to reproduce
------------------

Hey I am just getting started with speech recignition and i was just checking some basic examples that i had found 
 It was nothing too complicated, very simple things  
The code i am using is below : 

```python
import speech_recognition as sr

# Record Audio
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)
 
# Speech recognition using Google Speech Recognition
try:
    # for testing purposes, we're just using the default API key
    # to use another API key, use `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
    # instead of `r.recognize_google(audio)`
    print("You said: " + r.recognize_google(audio))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))
```
Expected behaviour

I expect it to just use my microphone and let me record something. 
------------------

(What did you expect to happen?)

Actual behaviour

This is the error i get, 
```Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):

  File "<ipython-input-9-2b39d94ceb5b>", line 1, in <module>
    runfile('/home/sanwal092/Desktop/Python/SR/dummy.py', wdir='/home/sanwal092/Desktop/Python/SR')

  File "/home/sanwal092/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/home/sanwal092/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/sanwal092/Desktop/Python/SR/dummy.py", line 14, in <module>
    with sr.Microphone() as source:

  File "/home/sanwal092/anaconda3/lib/python3.6/site-packages/speech_recognition/__init__.py", line 78, in __init__
    self.pyaudio_module = self.get_pyaudio()

  File "/home/sanwal092/anaconda3/lib/python3.6/site-packages/speech_recognition/__init__.py", line 109, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")

AttributeError: Could not find PyAudio; check installation
```

When i run import pyauaudio as p;print(p.__version__)"`.) to  check the version of pyaudio installed, i get the following error instead of the library working. 
```
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):

  File "<ipython-input-11-b37da17f237b>", line 1, in <module>
    import pyaudio

  File "/home/sanwal092/pyaudio/build/lib.linux-x86_64-2.7/pyaudio.py", line 116, in <module>
    import _portaudio as pa

  ImportError: /home/sanwal092/pyaudio/build/lib.linux-x86_64-2.7/_portaudio.so: undefined symbol: _Py_ZeroStruct
```
----------------

(What happened instead? How is it different from what you expected?)
I am not sure  where the error is coming from. It must have something to do with my compilation of the libray maybe and i am not sure what to do from here on. Anyhelp would be appreciated
```
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

(Delete all the statements that don't apply.)

My **system** is Ubuntu 16.04 LTS x64

My **Python version** is Python 3.6.0 :: Anaconda 4.3.1 (64-bit)

My **Pip version** is pip 9.0.1 

My **SpeechRecognition library version** is 3.6.5

**Comment by gotsanity** [comment] 2017-06-03 08:41
Not one of the maintainers but you are missing a dependency of pyaudio (libportaudio). On linux just do the following:
`sudo apt-get install libportaudio-dev`

**Comment by Uberi** [comment] 2017-06-03 09:44
Thanks @gotsanity! Just to add to that, if you get an error like `Package 'libportaudio-dev' has no installation candidate` with that command, try `sudo apt-get install portaudio19-dev` instead.

**Comment by sanster9292** [comment] 2017-06-03 13:27
Hey guys thanks a lot for the reply. I did get the no installation candidate error and when i tried your solution, it would seem that it is already installed. Following is the message i got 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
portaudio19-dev is already the newest version (19+svn20140130-1build1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.8.0-36 linux-headers-4.8.0-36-generic linux-headers-4.8.0-49
  linux-headers-4.8.0-49-generic linux-image-4.8.0-36-generic
  linux-image-4.8.0-49-generic linux-image-extra-4.8.0-36-generic
  linux-image-extra-4.8.0-49-generic linux-signed-image-4.8.0-36-generic
  linux-signed-image-4.8.0-49-generic pycharm-data snap-confine
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 32 not upgraded.

**Comment by Uberi** [comment] 2017-06-04 00:40
Hi @sanster9292,

How are you installing PyAudio? From source? Using pip?

If so, did you do so using the `sudo apt-get install portaudio19-dev python-all-dev python3-all-dev && sudo pip install pyaudio` command mentioned in the README?

**Comment by sanster9292** [comment] 2017-06-04 14:39
I have tried installing it from both. At this point i am not sure which one i used on my latest try. Is there a way where i could remove it completely and star over and see if that might fix it?

**Comment by Uberi** [comment] 2017-06-26 03:47
Hi @sanster9292,

You'll want to remove the pip version using `pip uninstall pyaudio`, and the package using `sudo apt-get purge python-pyaudio`. After that, using the commands above should do the trick.

**Comment by sanster9292** [comment] 2017-07-07 19:26
Hey guys sorry for the late reply. I tried your methods and it sorted out the problem. I now have SR working on my system. YAYYYYY.

I can run it through terminal but i cant seem to run it in Spyder. In  Spyder, it still gives me that very same error. I prefer working in visual debuggers. Does anyone have an idea why it might not be working in Spyder. Or if there are any other visual text editor/debuggers i should try instead.

**Comment by Uberi** [comment] 2017-07-08 22:17
Hi @sanster9292,

Spyder is likely running a different Python - are you running things in a virtualenv? With the same Python binary each time?

**Comment by esterrrg** [comment] 2017-09-12 02:20
HI, i tried the method mentioned, to remove and use the command to install. however, i got these while trying to install pyaudio.

> Cannot fetch index base URL https://pypi.python.org/simple/
>   Could not find any downloads that satisfy the requirement pyaudio
> Cleaning up...
> No distributions at all found for pyaudio
> Storing debug log for failure in /home/psl/.pip/pip.log

Whats wrong and what can I do? 
Thank you.

**Comment by sanster9292** [comment] 2017-09-12 05:43
I am not sure what you are doing wrong here. Seems like some intermittent step wasn't done properly. I would suggest you completely remove pyaudio from your system and reinstall using pip install. That is what i did and it worked for me

**Comment by esterrrg** [comment] 2017-09-12 05:47
Hi I have solved the problem and successfully installed pyaudio. However, it is under the package for python 3.4, but the interpreter im using is python3.5, how can I upgrade the pyaudio version to use it for python 3.5? 

Current Pyaudio ver is 0.2.7

**Comment by esterrrg** [comment] 2017-09-12 06:00
Hi I have installed Pyaudio already, but found it under python 3.4 package library, but the one i am using is anaconda3, python 3.5. How can I install it in a way that it will be inside the python3.5 interpreter?

**Comment by esterrrg** [comment] 2017-09-12 06:18
Hi I successfully installed Pyaudio, however i need Pyaudio 0.2.9 instead of 0.2.7, how can I upgrade the version?

**Comment by Uberi** [comment] 2017-09-13 02:30
Hi @esterrrg,

If you installed it using Pip, simply do `pip install --upgrade pyaudio`. If you installed from an egg, wheel, or setup.py, download the latest version of the egg/wheel/source code and install it again.

**Comment by Uberi** [comment] 2017-12-05 10:44
Seems like the issue was resolved! I'll close this now, but feel free to reopen if anything else goes wrong.

**Closed by Uberi** 2017-12-05 10:44 UTC

**Comment by nimeshrajput5211** [comment] 2017-12-27 08:52
HOw to download pyaudio for windows...anyone please help me...

**Comment by aritra-bhawani** [comment] 2018-09-30 13:58
Traceback (most recent call last):
  File "/Users/aritrabhawani/Desktop/iwork/python/NLTK/speech_to_text.py", line 5, in <module>
    with sr.Microphone() as source:
  File "/Users/aritrabhawani/miniconda3/lib/python2.7/site-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/Users/aritrabhawani/miniconda3/lib/python2.7/site-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

**Comment by aritra-bhawani** [comment] 2018-09-30 14:01
am on OS X device and this is the error message coming:

Traceback (most recent call last):
  File "/Users/aritrabhawani/Desktop/iwork/python/NLTK/speech_to_text.py", line 5, in <module>
    with sr.Microphone() as source:
  File "/Users/aritrabhawani/miniconda3/lib/python2.7/site-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/Users/aritrabhawani/miniconda3/lib/python2.7/site-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

i have already installed PyAudio and it was successfully installed, but this is the message am getting
can anyone help! Thank you

**Comment by sanster9292** [comment] 2018-10-01 03:47
Hmmm. I am going off of memory here, because I fixed the same issue a couple of months ago. 
Where did you install PyAudio from

**Comment by saket13** [comment] 2018-10-09 20:54
@aritra-bhawani Have you  installed xcode on your mac os prior to installing pyaudio

**Comment by eyun89** [comment] 2019-01-21 20:52
@killerPhoenix @aritra-bhawani I was able to work through this issue by installing ![PortAudio](http://www.portaudio.com/). If you happen to be using the ![Anaconda](https://anaconda.org/) distribution, `conda install -c anaconda portaudio` worked for me, ![PyAudio](https://people.csail.mit.edu/hubert/pyaudio/)  led me to the solution. Hope this helps.

**Comment by amithsam** [comment] 2019-05-15 17:21
AttributeError: Could not find PyAudio; check installation
i get this error when im trying to run my code i tried to install pyaudio but that doesnt work too.

**Comment by sanster9292** [comment] 2019-05-18 16:30
@amithsam where are you downloading your repository from

**Comment by amithsam** [comment] 2019-05-18 16:35
@sanster9292 i tried pip install its shows another error about Microsoft visual c++ required...

**Comment by sanster9292** [comment] 2019-05-19 17:10
I don't think I came across that error. You might want to start a new issue here with steps to reproduce that error. This issue is closed and might not get as much attention from the community. Once  you post a new issue, we could all take a look

**Comment by pecaso** [comment] 2019-06-09 07:28
https://stackoverflow.com/questions/54998028/how-do-i-install-pyaudio-on-python-3-7

i meet same problem with you 
and you can refer to the above link
the problem can be resolved

**Comment by Vishesht** [comment] 2019-06-21 13:48
Follow my step to solve the problem
pip install pipwin
pipwin install pyaudio

**Comment by SteveRogers37** [comment] 2019-07-03 19:02
Same Problem In Windows 10 Please Help To Install PyAudio
Error While Running Code:
File "c:/Users/Rogers/Desktop/Project/Ultron/ultron.py", line 43, in takeCommandommand    with sr.Microphone() as source:                                         t__.py", line 79, in __init  File "C:\Program Files\Python37\lib\site-packages\speech_recognition\__init__.py", line 79, in __init__    self.pyaudio_module = self.get_pyaudio()                                t__.py", line 110, in get_p  File "C:\Program Files\Python37\lib\site-packages\speech_recognition\__init__.py", line 110, in get_pyaudio    raise AttributeError("Could not find PyAudio; check installation")      
AttributeError: Could not find PyAudio; check installationPS C:\Users\Rogers\Desktop\Project\Ultron>

**Comment by sujoyroyskr** [comment] 2019-08-22 09:24
> Follow my step to solve the problem
> pip install pipwin
> pipwin install pyaudio

This worked for me .. CHEERS

**Comment by tulioreisc** [comment] 2019-08-30 00:49
> Follow my step to solve the problem
> pip install pipwin
> pipwin install pyaudio

I was having the same problem using Windows 10 and this somehow solved my problem. Thanks!

**Comment by koutsocheras99** [comment] 2019-09-11 00:15
> Follow my step to solve the problem
> pip install pipwin
> pipwin install pyaudio

Solved my problem for me too after trying for hours (Win 10) . Thanks alot !!

**Comment by TheBdouilleur** [comment] 2019-11-21 19:37
>Follow my step to solve the problem
>pip install pipwin
>pipwin install pyaudio

Solved my problem for me too (Win 10) . 
@Vishesht Thanks alot !! You Genius !!!

**Comment by TheBdouilleur** [comment] 2019-11-21 19:37
Its just magical !!!!

**Comment by Splodgebox** [comment] 2020-01-18 14:54
> Follow my step to solve the problem
> pip install pipwin
> pipwin install pyaudio

You are a legend, thanks man

**Comment by whateverittakes123Dennismuasyawambua** [comment] 2020-03-08 13:51
pip install pipwin
pipwin install pyaudio

didn't work returns

ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 480, in prepare_linked_requirement
    local_path = unpack_url(
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 278, in unpack_url
    return unpack_file_url(link, location, download_dir, hashes=hashes)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 251, in unpack_file_url
    unpack_file(from_path, location, content_type)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\utils\unpacking.py", line 249, in unpack_file
    unzip_file(
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\utils\unpacking.py", line 114, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "c:\users\admin\appdata\local\programs\python\python38\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by LauraOrozco** [comment] 2020-06-02 15:14
pip install pipwin 
pipwin install pyaudio

**Comment by Sapi5** [comment] 2020-06-20 11:06
> Follow my step to solve the problem
> pip install pipwin
> pipwin install pyaudio

it really helped  a lot.....Thanks Brother :)

**Comment by av1shek** [comment] 2020-07-10 17:09
> This command works very well on windows 10
> 
> pip install pipwin
> pipwin install pyaudio

Really helpful bro

**Comment by Arpanrc901** [comment] 2020-07-18 15:46
File "<ipython-input-2-a29514d3d9ba>", line 1
    pip install pipwin
              ^
SyntaxError: invalid syntax

**Comment by Arpanrc901** [comment] 2020-07-18 15:46
pip install pipwin
pipwin install pyaudio


File "", line 1
pip install pipwin
^
SyntaxError: invalid syntax

**Comment by elvinaqa** [comment] 2020-07-28 09:43
first
pip install pipwin
then
pipwin install pyaudio

**Comment by shanaya5855** [comment] 2020-08-01 14:21
Same happened to me. 
Then I used **pip install pyaudio** and it worked fine.
Hope this help you too! :")

**Comment by JirsaJam** [comment] 2020-08-12 18:24
got it to work on mac

`brew install portaudio
pip install pyaudio`

**Comment by jaydeep-shingala** [comment] 2020-08-31 09:52
I tried everything from pipwin to unofficial binary file installation and tried everything.
still in cmd : import pyaudio is working 
but if i write import pyaudio in python IDLE it;s not working.............


please help

**Comment by Vishesht** [comment] 2020-08-31 10:33
mail your code to me

**Comment by jaydeep-shingala** [comment] 2020-08-31 11:22
The code is as below

but also here please note that when i write import pyaudio in cmd it
workes properly.but if i write import pyaudio in python shell than it
is not working and says oduleNotFoundError: No module named 'pyaudio'


import speech_recognition as sr
# Record Audior = sr.Recognizer()with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)
 # Speech recognition using Google Speech Recognitiontry:
    # for testing purposes, we're just using the default API key
    # to use another API key, use `r.recognize_google(audio,
key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
    # instead of `r.recognize_google(audio)`
    print("You said: " + r.recognize_google(audio))except sr.UnknownValueError:
    print("Google Speech Recognition could not understand
audio")except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition
service; {0}".format(e))

**Comment by Teshan-Sachintha** [comment] 2020-10-22 15:08
Why did you commented the second row in the code.It must be in the code to work.And you are not assign the right varible for the microphone.
In you code you say:
```
# Record Audior = sr.Recognizer() 
with sr.Microphone() as source:
```
First get rid of comment symbol #
if you assign sr.Recognizer as Record Audior You must "r" in the rows to 'Record Audior'

```
audio = r.listen(source)
print("You said: " + r.recognize_google(audio))except sr.UnknownValueError:
```
Next thing is Some indenting of yours are wrong.
and although you use "except" in these rows-
```
try: #(You haven't add try into you code though there are two excepts)
     print("You said: " + r.recognize_google(audio))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))
```

**Comment by Teshan-Sachintha** [comment] 2020-10-22 15:14
If pyaudio doesn't work.
```
try:
     import pyaudio
except Exception as err:
     print(err)
```
Try this in your code.It will show you the error if it is in import pyaudio without Tracebaking.
then try again
`pip uninstall pyaudio`
`pip install pyaudio`
If doesn't work work
`pip install pipwin`
`pipwin insatll pyaudio`

**Comment by freesuden** [comment] 2020-11-11 14:53
import speech_recognition as sr                       (#bu kod'da bu hatayı veriyor) 

invalid syntax (__init__.py, line 109)

yardımcı olursanız sevinirim

**Comment by vephito** [comment] 2020-11-11 15:14
> Same Problem In Windows 10 Please Help To Install PyAudio
> Error While Running Code:
> File "c:/Users/Rogers/Desktop/Project/Ultron/ultron.py", line 43, in takeCommandommand with sr.Microphone() as source: t__.py", line 79, in __init File "C:\Program Files\Python37\lib\site-packages\speech_recognition__init__.py", line 79, in **init** self.pyaudio_module = self.get_pyaudio() t__.py", line 110, in get_p File "C:\Program Files\Python37\lib\site-packages\speech_recognition__init__.py", line 110, in get_pyaudio raise AttributeError("Could not find PyAudio; check installation")
> AttributeError: Could not find PyAudio; check installationPS C:\Users\Rogers\Desktop\Project\Ultron>

The pipwin method works try that

**Comment by GUHAN1990** [comment] 2020-12-31 15:00
With the shared solutions and my best try with few known libraries on pyaudio installation through, 
pip install pipwin
pipwin install pyaudio

found below error:
Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\GUHAN\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GUHAN\\AppData\\Local\\Temp\\pip-i
nstall-xy7ct8xh\\pyaudio_bbd679d0a37f4668a06bfb22d85c16dd\\setup.py'"'"'; __file__='"'"'C:\\Users\\GUHAN\\AppData\\Local\\Temp\\pip-install-xy7ct8xh\\pyaudio_bbd679d0a37f4668a06bfb22d85c1
6dd\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_w
heel -d 'C:\Users\GUHAN\AppData\Local\Temp\pip-wheel-nsc0tuas'
       cwd: C:\Users\GUHAN\AppData\Local\Temp\pip-install-xy7ct8xh\pyaudio_bbd679d0a37f4668a06bfb22d85c16dd\
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  copying src\pyaudio.py -> build\lib.win32-3.7
  running build_ext
  building '_portaudio' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  creating build\temp.win32-3.7\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\GUHAN\AppData\Local\Programs\Python\Python37-32\include -IC:\Users\GUHAN
\AppData\Local\Programs\Python\Python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt"
"-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include
\10.0.10240.0\winrt" /Tcsrc/_portaudiomodule.c /Fobuild\temp.win32-3.7\Release\src/_portaudiomodule.obj
  _portaudiomodule.c
  src/_portaudiomodule.c(29): fatal error C1083: Cannot open include file: 'portaudio.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
  src/_portaudiomodule.c(29): fatal error C1083: Cannot open include file: 'portaudio.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\GUHAN\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\
\GUHAN\\AppData\\Local\\Temp\\pip-install-xy7ct8xh\\pyaudio_bbd679d0a37f4668a06bfb22d85c16dd\\setup.py'"'"'; __file__='"'"'C:\\Users\\GUHAN\\AppData\\Local\\Temp\\pip-install-xy7ct8xh\\py
audio_bbd679d0a37f4668a06bfb22d85c16dd\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code,
__file__, '"'"'exec'"'"'))' install --record 'C:\Users\GUHAN\AppData\Local\Temp\pip-record-t1uqyhnn\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:
\Users\GUHAN\AppData\Local\Programs\Python\Python37-32\Include\pyaudio' Check the logs for full command output.



>>>>>>>>>> COFIRMS THAT No file named "portaudio.h",
AS WELL UNABLE TO access the portaudio.h functions through private downloading of portaudio.h. 

>>>>>>>>>> Please share your if any resolution to make pycharm aware to take voice inputs through speech_recognition.Microphone()  function

**Comment by frankysuper242** [comment] 2021-01-24 11:27
Hello Everyone,

I was working on a youtube project about Building your own Alexa. The problem is none of the advices are working for me.
Below installation is resulting to an error. As adviced by the youtuber He mentioned about using Python ver 3.6.0, I am using the latest version 3.9.1. 

pip install PyAudio
pip install pipwin
pipwin install pyaudio

I'd love to get the old version of Python 3.6.2 but I could not even find it in the interweb. (I'd love to learn to switch between 2 Python environments but I think I am stuck with the latest version and I couldn't even solve the issue.)

Please HELP! :(

(venv) C:\Users\USER\PycharmProjects\romanticAlexi>pip install pipwin
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong ve
rsion number (_ssl.c:1123)'))': /simple/pipwin/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong ve
rsion number (_ssl.c:1123)'))': /simple/pipwin/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong ve
rsion number (_ssl.c:1123)'))': /simple/pipwin/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong ve
rsion number (_ssl.c:1123)'))': /simple/pipwin/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong ve
rsion number (_ssl.c:1123)'))': /simple/pipwin/
Could not fetch URL https://pypi.org/simple/pipwin/: There was a problem confirming the
 ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded
with url: /simple/pipwin/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER]
wrong version number (_ssl.c:1123)'))) - skipping
ERROR: Could not find a version that satisfies the requirement pipwin
ERROR: No matching distribution found for pipwin
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ss
l certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded wit
h url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong
version number (_ssl.c:1123)'))) - skipping

Thank You in advance.

**Comment by New-dev0** [comment] 2021-02-06 11:11
> Follow my step to solve the problem
> pip install pipwin
> pipwin install pyaudio

I Got this !!
pipwin : The term 'pipwin' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of    
the name, or if a path was included, verify that the path is correct and try again.

**Comment by Justcodeit2** [comment] 2021-04-07 23:05
WINDOWS

pip install pipwin
pipwin install pyaudio
This will install pyaudio
