### ISSUE TITLE
intentionally printing 'result2' on recognize_google()?

### ISSUE THREAD

**Issue by ako2cjairo1** [Uberi/speech_recognition#652] opened 2023-01-12 05:10 UTC
Steps to reproduce
------------------

1. Always happens on response.
2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)
3. (If there are any files, like audio recordings, don't forget to include them.)

Expected behaviour
------------------

Don't log/print the response text, just return the result.

Actual behaviour
----------------

always printed in the console the result2 every response

<img width="428" alt="Screenshot 2023-01-12 at 1 05 15 PM" src="https://user-images.githubusercontent.com/55369888/211982516-8fa3b5de-eda2-4f2e-a4fc-ab0840052b99.png">

**Comment by TomKranenburg** [comment] 2023-01-12 12:30
Yeah getting this result too. Was just about to patch it. Is this expected behaviour?

**Comment by ftnext** [comment] 2023-01-12 14:57
@ako2cjairo1 Thanks for writing this Issue.

This Issue seems to be a duplicate of #645, so I'm closing it.
These issues will be fixed in #651.

I don't know the reason for these print functions, but it seems to be added in this pull request https://github.com/Uberi/speech_recognition/pull/434.
I agree with removing them.

**Closed by ftnext** 2023-01-12 14:57 UTC
Labels: duplicate
