### ISSUE TITLE
Tweeking variables in pocketsphinx [Question]

### ISSUE THREAD

**Issue by Naki21** [Uberi/speech_recognition#254] opened 2017-08-02 16:52 UTC
So this is just a general question but I'm having a hard time understanding how I would go about calibrating pocketsphinx within the context of this module. I'm sure it is possible but I just don't know how to start. I would like to be able to tweek variables to be able to start adjusting for accuracy and what not. Any idea on how I would get started?

Ubuntu 16.04

**Comment by Uberi** [comment] 2017-12-05 09:48
Hi @Naki21,

This module doesn't really expose many knobs, by design, so in these cases I would recommend simply [using the code for `recognize_sphinx`](https://github.com/Uberi/speech_recognition/blob/6f61f6b33a1105fe478ad3e762e05447f26c97f9/speech_recognition/__init__.py#L755) as a basis for your own implementation!

There isn't that much code to it - almost all of this module actually deals with the audio processing that takes place before you call `recognize_sphinx`. As for tweaking settings, I would start with the [decoder config](https://github.com/Uberi/speech_recognition/blob/6f61f6b33a1105fe478ad3e762e05447f26c97f9/speech_recognition/__init__.py#L798). I'll close this now, but feel free to reopen if you have any other questions!

**Closed by Uberi** 2017-12-05 09:48 UTC
